clear all
addpath('C:\Program Files\MATLAB\R2017b\satools')
%
ST_cons(1,:) = {'c1', 'c2', 'c3', 'd4', 'd5', 'm6', 'm7'};
ST_cons(2,:) = {'c_1', 'c_2', 'c_3', 'c_4', 'c_5', 'c_6', 'd_7', 'd_8', 'd_9', 'd_10', 'd_11', 'd_12', 'm_13', 'm_14', 'm_15'};

ST_cons(3,:) = {...
    '0 = dtheta1 - w1', ...
    '0 = J1*dw1 - u + b1*w1 + k1*(theta1-theta2) + d',...
    '0 = dtheta2 - w2', ...
    '0 = J2*dw2 + b2*w2 + k1*(theta2-theta1) + k2*(theta2-theta3)', ...
    '0 = dtheta3 - w3', ...
    '0 = J3*dw3 + b3*w3 + k2*(theta3-theta2)', ...
    '0 = dtheta1 - D(theta1)', ...
    '0 = dw1 - D(w1)', ...
    '0 = dtheta2 - D(theta2)', ...
    '0 = dw2 - D(w2)', ...
    '0 = dtheta3 - D(theta3)', ...
    '0 = dw3 - D(w3)', ...
    '0 = y1 - theta1', ...
    '0 = y2 - theta2', ...
    '0 = y3 - theta3',...
    };

ST_input(1,1) = {'u'};
ST_input(2,1) = {'u'}; % LaTeX
ST_meas(1,:) = {'y1', 'y2', 'y3'};
ST_meas(2,:) = {'y_1', 'y_2', 'y_3'}; % LaTeX
ST_par(1,:)    = {'b1','b2','b3','k1','k2','J1','J2','J3'};
ST_par(2,:)    = {'b_1','b_2','b_3','k_1','k_2','J_1','J_2','J_3'};%LaTeX
ST_unknowns(1,:) = {'theta1', 'dtheta1', 'w1', 'dw1', 'theta2', 'dtheta2', 'w2', 'dw2','theta3', 'dtheta3', 'w3', 'dw3' , 'd' };
ST_unknowns(2,:) = {'\\theta_1', '\\dot{\\theta_1}', '\\omega_1', '\\dot{\\omega_1}', '\\theta_2', '\\dot{\\theta_2}', '\\omega_2', '\\dot{\\omega_2}','\\theta_3', '\\dot{\\theta_3}', '\\omega_3', '\\dot{\\omega_3}', 'd' };

ST_canfail= [1:6, 13:15]; % constraint c6 cannot fail
ST_domains= ones(1,15);
cons_oneway= {[],[],[],[],[],[],{'theta1'},{'w1'},{'theta2'},{'w2'},{'theta3'},{'w3'},[],[],[]};
ST_IncMat = sa_incidencematrix(ST_cons,...
                                    ST_input,ST_meas,...
                                    ST_unknowns,cons_oneway);

  
ST_sys =...
    sa_create(ST_IncMat,ST_cons,...
    ST_input, ST_meas,ST_unknowns,...
    ST_domains, ST_canfail);

sa_disp(ST_sys);

ST_sys=sa_match(ST_sys,'rank');

% Autogenerate pdf report - requires LaTeX to be installed
sa_report(ST_sys,'Assig','pdf','analytic_expressions',true);
disp('A report has been generated with the following results:')

disp('Obtained matching:');
sa_disp(ST_sys, 't');

disp('Parity relation symbolic form:')
sa_disp(ST_sys, 's');

disp('Parity relation analytic form:')
sa_disp(ST_sys, 'a');